behaviors:
    Autopark:
        trainer_type: ppo
        hyperparameters:
            batch_size: 512 
            buffer_size: 5120
            learning_rate_schedule: linear
            learning_rate: 3.0e-4
        network_settings:
            hidden_units: 512
            normalize: false
            num_layers: 4

        max_steps: 10.0e6
        time_horizon: 64    
        summary_freq: 10000
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99

        
                

